//do not edit this files sinces it has been autogenerated by importCardsDocument.ts
import { CardData } from './PlayerData';
export const classifiedCards:Array<CardData> = [
  {
    "name": "OECD Learning Compass 2030",
    "desc": "Der ganz große Überblick: Wohin entwickelt sich das lernen weltweit?",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      },
      {
        "type": "motivation",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "darkgreen"
  },
  {
    "name": "Reflexion von Fachanforderungen",
    "desc": "\"Was? Das soll ich alles unterrichten?\" Die Beschäftigung mit den Fachanforderungen unterstützt Dich bei der Strukturierung der Unterrichtsinhalte.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "darkgreen"
  },
  {
    "name": "Bildung für nachhaltige Entwicklung",
    "desc": "Du förderst das verantwortungsvolle Denken und Handeln Deiner Schüler*innen im regionalen und globalen Kontext",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "group": "darkgreen"
  },
  {
    "name": "Bildungsbegriff nach Klafki",
    "desc": "Die Fähigkeiten zur Selbstbestimmung, zur Mitbestimmung und zur Solidarität stellen laut Klafki drei wesentliche Elemente von Bildung dar.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "group": "darkgreen"
  },
  {
    "name": "Bildungsgehalt des Fachs",
    "desc": "Warum wird Dein Fach eigentlich an Schulen unterrichtet?",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "group": "darkgreen"
  },
  {
    "name": "Konstruktivistische Unterrichtsmethoden",
    "desc": "Du lernst Methoden kennen, die Schüler*innen bei der selbstorganisierten Konstruktion von Wissen unterstützen.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "group": "blue"
  },
  {
    "name": "COACTIV-Dimensionen der Unterrichtsqualität",
    "desc": "Die Forschung zeigt Dir, was Unterricht ausmacht: effiziente Klassenführung, kognitive Aktivierung und konstruktive Unterstützung",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "blue"
  },
  {
    "name": "Hattie-Studie",
    "desc": "Die große Meta-Studie zeigt: Ein zentraler Faktor für den Lernerfolg sind professionelle Lehrkräfte!",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 2
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "blue"
  },
  {
    "name": "Helmkes Angebots-Nutzungsmodell",
    "desc": "Helmke beschreibt Unterricht als ein Angebot für Schüler*innen, dessen Nutzung von vielen Einflussfaktoren abhängt.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "blue"
  },
  {
    "name": "Merkmale guten Unterichts",
    "desc": "Nach Meyer stellt die klare Strukturierung des Unterrichts eines von insgesamt zehn Merkmale guten Unterrichts dar.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      },
      {
        "type": "motivation",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "blue"
  },
  {
    "name": "Basisdimensionen von Unterrichtsqualität",
    "desc": "Tiefenmerkmale wie eine effektive Klassenführung, kognitive Aktivierung und konstruktive Unterstützung entscheiden über die Unterrichtsqualität.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "yellow"
  },
  {
    "name": "Sicht- und Tiefenstrukturen im Unterricht",
    "desc": "Sichtstrukturen betreffen Rahmenbedingungen und Methodik des Unterrichts, Tiefenstrukturen beschreiben den Lehr-Lernprozess und die sozialen Beziehungen",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "yellow"
  },
  {
    "name": "Unterrichtsbeobachtungsinstrumente",
    "desc": "Du lernst, Klassenführung, kognitive Aktivierung und konstruktive Unterstützung im Unterricht zu analysieren",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      },
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "group": "yellow"
  },
  {
    "name": "Videoanalyse",
    "desc": "Der Mehrwert der videogestützen Unterrichtsanalyse wird Dir am Beispiel von instruktionalen und problembasierten Lehr-Lern-Settings deutlich.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "group": "yellow"
  },
  {
    "name": "Unterrichtsforschung",
    "desc": "Unterricht lässt sich mit wissenschafltichen Methoden untersuchen. Diese Forschung kann Dir zeigen, was in Deinem Unterricht funktioniert.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      },
      {
        "type": "motivation",
        "value": 2
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "group": "yellow"
  },
  {
    "name": "Medieneinsatz",
    "desc": "Auswahl, Gestaltung und Einsatz von Medien erfordern Deine didaktischen Überlegungen und Deine Kreativität.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "group": "violet"
  },
  {
    "name": "Cognitive Load",
    "desc": "Du weißt die kognitive Belastung in Lernangeboten und Aufgaben für Deine Schüler*innen lernförderlich zu steuern.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "group": "violet"
  },
  {
    "name": "Medienbildung",
    "desc": "Dir wird klar, dass die Bildung mit und über Medien Teil der Allgemeinbildung für Schüler*innen ist!",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "group": "violet"
  },
  {
    "name": "OER - Open Educational Resources",
    "desc": "Freie Lizenzen und Formate lassen Dich Deine Arbeit mit der ganzen Welt teilen! Du entdeckst den Vorteil freier Bildungsmedien, nutzt, erstellst und teilst sie häufig.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 3,
    "totalInDeck": 1,
    "group": "violet"
  },
  {
    "name": "Drei-Speicher-Modell der Informationsverarbeitung",
    "desc": "Du siehst diese karte (sensorischer Speicher), Du erfasst die Infromation aktiv (Kurzzeitgedächtnis) und verknüpfst sie mit Dir bekannten Inhalten (Langzeitgedächtnis).",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "violet"
  },
  {
    "name": "Inklusion",
    "desc": "In deinem Studium wird das gemeinsame Lernen für alle Menschen - mit und ohne Behinderung - thematisiert.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 3,
    "totalInDeck": 1,
    "group": "rose"
  },
  {
    "name": "Didaktische Reduktion",
    "desc": "Wie kannst Du etwas vermitteln? Grundlage der didaktischen Strukturierung stellt die fachliche Klärung und das Erfassen von Lernendenperspektiven dar.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "group": "rose"
  },
  {
    "name": "Binnendifferenzierung",
    "desc": "Du weißt um die Unterschieldichkeit von Vorwissen, Interessen und Motivation der Schüler*innen und bist für individuelle lernbedürfnisse sensibilisiert.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "rose"
  },
  {
    "name": "Präkonzepte",
    "desc": "Die Unterscheidung von nützlichen Vorkenntnissen und fehlerhaften Vorstellungen der Schüler*innen erlaubt Dir, passende Lernangebote zu gestalten.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      },
      {
        "type": "motivation",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "rose"
  },
  {
    "name": "Konstruktivistische Lerntheorie",
    "desc": "Du erkennst, dass Lernen kein passives Speichern, sondern ein aktives Konstruieren von Wissen ist.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "rose"
  },
  {
    "name": "Umgang mit Störungen",
    "desc": "In der Theorie lernst Du, verschiedenen Störungen im Klassenzimmer zu begegnen.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 2
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "green"
  },
  {
    "name": "Selbstbestimmungstheorie der Motivation",
    "desc": "Das basic needs-Modell von Deci und Ryan zeigt Dir, dass sich eine auf Selbstbestimmung beruhende Lernmotivation positiv auf die Leistung auswirkt.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "green"
  },
  {
    "name": "Classroom Management",
    "desc": "Der Klassenraum ähnelt einem Orchester: Du als Lehrkraft musst die ganze Klasse im Blick behalten, für Struktur sorgen und die Lernmotivitation der Schüler*innen fördern.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "green"
  },
  {
    "name": "Themenzentrierte Interaktion",
    "desc": "Die Zusammenarbeit eine Gruppe wird durch die Person (Dich), die Gruppeninteraktion (Wir), die Aufgabe (Es) und das Umfeld (Globe) beeinflusst.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "green"
  },
  {
    "name": "5 Phasen der Gruppenentwicklung",
    "desc": "Du hattest Streit in einer Lerngruppe. Später lernst Du im Studium die Phasen der Gruppenentwicklung kennen und verstehst endlich, was da passiert ist.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "group": "green"
  },
  {
    "name": "Didaktisches Dreieck",
    "desc": "Schüler*in, Lehrer*in, Fachinhalt: Dir leuchtet ein, wie diese drei Komponenten das Unterrichtsgeschehen bestimmt und berücksichtigt werden müssen.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "grey"
  },
  {
    "name": "KMK-Standards für die Lerhkräftebildung",
    "desc": "Die Anforderungen für Lehrkräfte an Schulen gliedern sich in die Kompetnzbereiche Unterrichten, Erziehen, Bewerten und Innovieren.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "grey"
  },
  {
    "name": "Kompetenzmodell COACTIV",
    "desc": "Lehrkräfte verfügen als Teil ihrer professionellen Handlungskompetenz über viele Wissensfacetten, die vernetzt zur Anwendung kommen.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "grey"
  },
  {
    "name": "Kohärentes Wissen",
    "desc": "Dir gelingt es immer besser, die Wissensbestandteile aus Fachdidaktik, Fachwissenschaft und Bildungswissenschaften miteinander zu vernetzen.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 3
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "grey"
  },
  {
    "name": "Aufgabenentwicklung",
    "desc": "Deine Expertise lässt Dich Aufgaben entwickeln, die unterschiedliche Kompetenzen ansprechen und fördern",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "orange"
  },
  {
    "name": "Leistungsdiagnostik",
    "desc": "Das Messen, Bewerten und Fördern von Schüler*innenleistungen bedeutet, mehr als nur Noten von 1 bis 6 zu vergeben.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "orange"
  },
  {
    "name": "Wissen über Lernprozesse",
    "desc": "Deine Unterrichtsgestaltung profitiert von Deiner Kenntnis unterschiedlicher Lerntheorien.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "orange"
  },
  {
    "name": "Blooms Lernzieltaxonomie",
    "desc": "Erkenne und sprich verschiedene Stufen kognitiver Aktivitäten an!",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "orange"
  },
  {
    "name": "KMK-Kompetenzbereiche",
    "desc": "Die Kultusministerkonferenz gibt vor, welche Konpetenzen Schüler*innen erreichen sollen.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "orange"
  },
  {
    "name": "Kompetenzbegriff",
    "desc": "Dir ist inzwischen bekannt, dass es unterschiedliche Definitionen von Kompetenzen gibt, so z.B. die häufig verwendete nach Weinert.",
    "type": "theory",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "group": "orange"
  },
  {
    "name": "Schulbegleitung",
    "desc": "Indem Du ein Kind mit Förderbedarf in der Schule begleitest, erhälst Du eine neue Perspektive auf das Thema Inklusion.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      },
      {
        "type": "experience",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 3,
    "totalInDeck": 1,
    "socialForm": "solo"
  },
  {
    "name": "Tätigkeit als Hilfskraft",
    "desc": "Du abreitest als HiWi in deinem Fach und erhälst Einblicke in die Abläufe an der CAU.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      },
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "solo"
  },
  {
    "name": "Hausarbeit",
    "desc": "Deine Hausarbeit dreht sich um ein Dich brennend interessierendes Thema. Du investierst Zeit und Mühe, um Dich tief in Dein Thema einzuarbeiten.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "solo"
  },
  {
    "name": "Portfolio",
    "desc": "Du dokumentierst und reflektierst Deine Lernprozesse in einem studienbegleitenden Portfolio.",
    "type": "event",
    "properties": [
      {
        "type": "experience",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 2
      }
    ],
    "costs": 3,
    "totalInDeck": 1,
    "socialForm": "solo"
  },
  {
    "name": "Mitarbeit im AStA-Lehramtsreferat",
    "desc": "Im AStA stehst Du hochschulpolitisch für die Rechte und Interessen der Lehramtsstudierenden ein, berätst sie bei Unsicherheiten und schaffst Begegnungsräume.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 2
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "solo"
  },
  {
    "name": "Laborprotokoll",
    "desc": "Du investierst Zeit und Mühe, um Deine praktischen Arbeiten aus dem Labor auszuwerten und zu dokumentieren.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "solo"
  },
  {
    "name": "Hausaufgabenbetreuung",
    "desc": "Bei der Hausaufgabenbetreuung übst Du den Umgang mit Schüler*innen und ihren individuellen Lernhindernissen.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "solo"
  },
  {
    "name": "Auslandssemester",
    "desc": "Ein Semester lang studierst Du an einer Uni im Ausland, sammelst neue Eindrücke und lernst die Unterrichtskultur des Gastlandes kennen.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 3
      },
      {
        "type": "experience",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 4,
    "totalInDeck": 1,
    "socialForm": "solo"
  },
  {
    "name": "BELA",
    "desc": "Im bildungswissenschaftlichen Eingangsmoduls erhälst Du Einblicke in die Grundlagen des Lehrberufs - doch aller Anfang ist schwer.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "socialForm": "solo"
  },
  {
    "name": "Nebentätigkeit an einer Schule",
    "desc": "Du hast die Möglichkeit, an einer Schule als Aushilfs-Lehrkraft zu unterrichten. Du nimmst die Herausforderung an!",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "solo"
  },
  {
    "name": "Psychologische Beratung",
    "desc": "Du nimmst die psychologische Beratung des Studierendenwerks in Anspruch und findest neue Perspektiven.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "socialForm": "solo"
  },
  {
    "name": "ZfL-Zertifikat: Inklusive Schule",
    "desc": "Du erlebst inklusive Lernangebote an Schulen und wirst in Theorie und Praxis für das Thema Inklusion sensibilisiert.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "solo"
  },
  {
    "name": "Lehr-Lern-Labor in der Forschungswerkstatt",
    "desc": "Bei Micro-Teaching unterrichtest Du kleine Gruppen von Schüler*innen und kannst Dich als Lehrkraft erproben.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 2
      },
      {
        "type": "experience",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 3,
    "totalInDeck": 1,
    "socialForm": "solo"
  },
  {
    "name": "Sportliche Aktivität",
    "desc": "Während des Studiums treibst Du regelmäßig Sport, wobei Du dich körperlich verausgaben und Abstand zum Lernen gewinnen kannst.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 2
      }
    ],
    "costs": 1,
    "totalInDeck": 2,
    "socialForm": "solo"
  },
  {
    "name": "Weiterbildung im Einsatz digitaler Medien",
    "desc": "Du wirst für den digitalen Meideneinsatz im Unterricht vorbereitet.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 2,
    "socialForm": "solo"
  },
  {
    "name": "DaZ/DaF als Ergänzungsfach",
    "desc": "Dein Ergänzungsfach Deutsch als Zweit- und Fremdsprache bereitet Dich darauf vor, als Lehrkraft Integrationskurse geben zu können.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 2
      }
    ],
    "costs": 1,
    "totalInDeck": 2,
    "socialForm": "solo"
  },
  {
    "name": "Simulierter Klassenraum",
    "desc": "Im Simulierten Klassenraum kannst Du mit virtuellen Schüler*innen interagieren und Deine Diagnosefähigkeiten testen.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 2,
    "socialForm": "solo"
  },
  {
    "name": "Tätigkeit als Tutor*in",
    "desc": "Als Tutor*in an der CAU begleitest Du Studienanfänger*innen. Du kannst deine Erfahrungen weitergeben und Dich als Lehrperson ausprobieren.",
    "type": "event",
    "properties": [
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 2,
    "socialForm": "solo"
  },
  {
    "name": "Sitzungsmoderation",
    "desc": "Für die Moderation einer Lehrveranstaltungssitzung hast Du dir grundlegende Moderationstechniken angeeignet. Es wird ein Erfolg.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 2,
    "socialForm": "solo"
  },
  {
    "name": "Unterrichts-Hospitation",
    "desc": "Die Unterrichtsstunde einer Lehrkraft zu beobachten, schult den Blick. Auch den auf das eigene Lehrverhalten.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 2
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 2,
    "socialForm": "solo"
  },
  {
    "name": "Fachwissenschaftliche Klausur",
    "desc": "Umfangreiches Fachwissen ist die Grundlage jeder guten Lehrkraft: Da Du Dein Fach selbst gewählt hast, lernt es sich leichter… oder?",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      },
      {
        "type": "motivation",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "socialForm": "student-council"
  },
  {
    "name": "Fachschaftsarbeit",
    "desc": "Durch die Fachschaft knüpfst Du neue Kontakte und setzt Dich für die Anliegen Deiner Kommilition*innen ein.",
    "type": "event",
    "properties": [
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "socialForm": "student-council"
  },
  {
    "name": "Fachdidaktik-Veranstaltung",
    "desc": "Du beschäftigst Dich mit der Auswahl und der lernförderlichen Aufbereitung fachwissenschaftlicher Inhalte.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      },
      {
        "type": "motivation",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "socialForm": "student-council"
  },
  {
    "name": "Exkursion",
    "desc": "Die Verbindung von Theorie und Praxis an einem anderen Ort erweitert Deinen Horizont.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 2
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "socialForm": "student-council"
  },
  {
    "name": "Fachschaftsfeier",
    "desc": "Du hast Gelegenheit neue Kommilition*innen kennenzulernen, spannende Themen zu vertiefen und Dozent*innen privat zu sprechen.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 3
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "socialForm": "student-council"
  },
  {
    "name": "Referat",
    "desc": "Du hast die Aufgabe, Deinen Kommilition*innen ein Thema anschaulich zu vermitteln. Schaffst Du es, sie kognitiv zu aktivieren, wie Du es gelernt hast?",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "student-council"
  },
  {
    "name": "Fallbasiertes Lernen",
    "desc": "In einer fachdidaktischen Veranstaltung analysiert und diskutiert Ihr konkrete Unterrichtssituationen.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "student-council"
  },
  {
    "name": "Fachdidaktische Klausur",
    "desc": "Du stellst Dein theoretisches Wissen über das fachspezifische Lehren und Lernen unter Beweis.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 3
      },
      {
        "type": "motivation",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "student-council"
  },
  {
    "name": "Unterrichtsentwurf schreiben",
    "desc": "Die Planung von Unterrichtsstunden unter Berücksichtigung pädagogischer und didaktischer Theorien ist für Dich anfangs ganz schön aufwändig.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "student-council"
  },
  {
    "name": "Teststunde an einer Schule",
    "desc": "Du darfst mit Deiner Lerngruppe einen Unterrichtsentwurf an einer Schule testen. Nun findet Ihr heraus, ob Eure aufwändige Planung auch umsetzbar ist.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 3
      },
      {
        "type": "experience",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "student-council"
  },
  {
    "name": "Kombi-Modul",
    "desc": "Fachwissenschaft und Fachdidaktik gestalten gemeinsam ein Modul und Du lernst, wie Du aktuelle Wissenschaft für die Schule aufbereitest.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 1
      },
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "experience",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 3,
    "totalInDeck": 1,
    "socialForm": "student-council"
  },
  {
    "name": "Theaterbesuch",
    "desc": "Kultur und Bildung finden nicht nur an der Uni statt.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": 2
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "group"
  },
  {
    "name": "Vorlesungsfreie Zeit",
    "desc": "Die freie Zeit nutzt Du zur intensiven Erholung",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 3
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "socialForm": "group"
  },
  {
    "name": "Erste-Hilfe-Kurs",
    "desc": "Du nimmst an einem Erste-Hilfe-Kurs teil und kannst in Zukunft nicht nur Schüler*innen im Notfall helfen.",
    "type": "event",
    "properties": [
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "socialForm": "group"
  },
  {
    "name": "Teilnahme an einer Bildungsdemo",
    "desc": "Eine angekündigkte Bildungsreform missfällt Dir, weshalb Du mit Deinen Kommiliton*innen lautstark dagegen protestierst.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 2
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 2,
    "totalInDeck": 1,
    "socialForm": "group"
  },
  {
    "name": "Semesterabschlussparty",
    "desc": "Endlich ausspannen! Diesen Abschluss des Semesters hast du Dir verdient.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 3
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "socialForm": "group"
  },
  {
    "name": "Städtetrip",
    "desc": "In einer fremden Stadt sammelst Du neue Eindrücke und Erfahrungen und kannst darüber Dein Studium kurzzeitig mal vergessen.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": 2
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "socialForm": "group"
  },
  {
    "name": "Camping-Urlaub",
    "desc": "Ein ausgedehnter Camping-Urlaub lässt Euch Zeit für Gedanken abseits des Studiums.",
    "type": "event",
    "properties": [
      {
        "type": "knowledge",
        "value": -1
      },
      {
        "type": "motivation",
        "value": 1
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 1,
    "totalInDeck": 1,
    "socialForm": "group"
  },
  {
    "name": "Lerngruppe: Bibliothek",
    "desc": "In den Gruppenarbeitsräumen kommst Du mit Deinen Kommiliton*innen in einen ergiebigen fachlichen Austausch.",
    "type": "event",
    "properties": [],
    "costs": 1,
    "totalInDeck": 2,
    "socialForm": "group"
  },
  {
    "name": "Lerngruppe: Mensabesuch",
    "desc": "Die Mensa ist kein Sterne-Restaurant, aber meist gibt es leckeres Essen und fachlichen Austausch.",
    "type": "event",
    "properties": [],
    "costs": 1,
    "totalInDeck": 2,
    "socialForm": "group"
  },
  {
    "name": "Lerngruppe: Schrevenpark",
    "desc": "Beim gemeinsamen Lernen an der frischen Luft und unter Bäumen kann der Rauch aus Euren Köpfen schnell abziehen.",
    "type": "event",
    "properties": [],
    "costs": 1,
    "totalInDeck": 2,
    "socialForm": "group"
  },
  {
    "name": "Der Zweifel",
    "desc": "Du zweifelst an Deiner Entscheidung für's Lehramtsstudium… und beschließt weiterzumachen.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": -3
      },
      {
        "type": "empowerment",
        "value": 1
      }
    ],
    "costs": 0,
    "totalInDeck": 2,
    "socialForm": "negative-solo"
  },
  {
    "name": "Pauschale Geringschätzung des Lehramts",
    "desc": "Vormittags recht, nachmittags frei! Ihr werdet mit einem Vorurteil gegenüber Lehrkräften konfrontiert.",
    "type": "event",
    "properties": [
      {
        "type": "motivation",
        "value": -2
      }
    ],
    "costs": 0,
    "totalInDeck": 1,
    "socialForm": "negative-group"
  }
];